name: C/C++ CI

on: [push] 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8.0' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' 

    - name: install and configure Conan
      run: |
        sudo apt-get install python3-setuptools
        sudo python3 -m pip install conan
        conan profile new default --detect
        conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"

    - name: Configure project
      run: cmake -DCMAKE_BUILD_TYPE=Release .

    - name: Make project
      run: make 

    - name: Run tests
      run: ctest -C=Release 
